from datetime import datetime, timezone

PRODUCTS = [
    {
        "id": "p001",
        "name": "Tai nghe Bluetooth AirBeat S3",
        "slug": "tai-nghe-bluetooth-airbeat-s3",
        "description": "Tai nghe không dây chống ồn nhẹ, pin 28 giờ, phù hợp học online và làm việc.",
        "price": 459000,
        "original_price": 699000,
        "category": "Điện tử",
        "rating": 4.8,
        "sold_count": 2380,
        "stock": 86,
        "image_url": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Trắng", "Xanh navy"],
        "tags": ["tai nghe", "bluetooth", "duoi 500k"],
    },
    {
        "id": "p002",
        "name": "Bàn phím cơ KPro Mini",
        "slug": "ban-phim-co-kpro-mini",
        "description": "Bàn phím cơ layout 75%, switch êm, LED trắng, kết nối USB-C.",
        "price": 790000,
        "original_price": 990000,
        "category": "Điện tử",
        "rating": 4.7,
        "sold_count": 912,
        "stock": 42,
        "image_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Trắng"],
        "tags": ["ban phim", "van phong", "gaming"],
    },
    {
        "id": "p003",
        "name": "Chuột không dây MobiClick M2",
        "slug": "chuot-khong-day-mobiclick-m2",
        "description": "Chuột không dây nhỏ gọn, pin 6 tháng, click êm cho văn phòng.",
        "price": 189000,
        "original_price": 249000,
        "category": "Điện tử",
        "rating": 4.6,
        "sold_count": 3210,
        "stock": 150,
        "image_url": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Bạc", "Hồng"],
        "tags": ["chuot", "van phong", "duoi 200k"],
    },
    {
        "id": "p004",
        "name": "Đồng hồ thông minh FitNow Lite",
        "slug": "dong-ho-thong-minh-fitnow-lite",
        "description": "Theo dõi nhịp tim, giấc ngủ, 80 chế độ luyện tập, chống nước IP68.",
        "price": 890000,
        "original_price": 1290000,
        "category": "Điện tử",
        "rating": 4.5,
        "sold_count": 678,
        "stock": 35,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Hồng", "Xanh rêu"],
        "tags": ["smartwatch", "suc khoe", "the thao"],
    },
    {
        "id": "p005",
        "name": "Pin dự phòng VoltGo 10000mAh",
        "slug": "pin-du-phong-voltgo-10000mah",
        "description": "Sạc nhanh 20W, 2 cổng USB-C/USB-A, vỏ mỏng dễ mang theo.",
        "price": 329000,
        "original_price": 449000,
        "category": "Điện tử",
        "rating": 4.9,
        "sold_count": 1844,
        "stock": 98,
        "image_url": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Trắng"],
        "tags": ["pin du phong", "sac nhanh", "du lich"],
    },
    {
        "id": "p006",
        "name": "Balo laptop UrbanPack 15",
        "slug": "balo-laptop-urbanpack-15",
        "description": "Balo chống nước, ngăn laptop 15.6 inch, nhiều ngăn phụ cho đi làm.",
        "price": 419000,
        "original_price": 590000,
        "category": "Thời trang",
        "rating": 4.8,
        "sold_count": 1260,
        "stock": 64,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Xám", "Xanh navy"],
        "tags": ["balo", "laptop", "di lam"],
    },
    {
        "id": "p007",
        "name": "Giày sneaker DailyStep",
        "slug": "giay-sneaker-dailystep",
        "description": "Sneaker đế nhẹ, form basic, phối đồ đi học và đi làm.",
        "price": 549000,
        "original_price": 720000,
        "category": "Thời trang",
        "rating": 4.6,
        "sold_count": 2044,
        "stock": 73,
        "image_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80",
        "variants": ["39", "40", "41", "42", "43"],
        "tags": ["giay", "sneaker", "daily"],
    },
    {
        "id": "p008",
        "name": "Áo thun CottonFlex basic",
        "slug": "ao-thun-cottonflex-basic",
        "description": "Áo thun cotton co giãn, dày vừa, không xù lông sau nhiều lần giặt.",
        "price": 159000,
        "original_price": 220000,
        "category": "Thời trang",
        "rating": 4.7,
        "sold_count": 5320,
        "stock": 210,
        "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
        "variants": ["S", "M", "L", "XL"],
        "tags": ["ao thun", "basic", "cotton"],
    },
    {
        "id": "p009",
        "name": "Kem chống nắng SunCare SPF50",
        "slug": "kem-chong-nang-suncare-spf50",
        "description": "Kết cấu mỏng nhẹ, không nâng tone quá nhiều, phù hợp da dầu.",
        "price": 259000,
        "original_price": 340000,
        "category": "Làm đẹp",
        "rating": 4.8,
        "sold_count": 2876,
        "stock": 120,
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
        "variants": ["50ml"],
        "tags": ["chong nang", "skincare", "da dau"],
    },
    {
        "id": "p010",
        "name": "Serum HA GlowSkin",
        "slug": "serum-ha-glowskin",
        "description": "Serum cấp ẩm Hyaluronic Acid, hỗ trợ da căng bóng và dịu nhẹ.",
        "price": 319000,
        "original_price": 429000,
        "category": "Làm đẹp",
        "rating": 4.7,
        "sold_count": 1465,
        "stock": 57,
        "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
        "variants": ["30ml"],
        "tags": ["serum", "duong am", "skincare"],
    },
    {
        "id": "p011",
        "name": "Máy xay mini FreshCup",
        "slug": "may-xay-mini-freshcup",
        "description": "Máy xay sinh tố cá nhân, sạc USB, dung tích 350ml.",
        "price": 299000,
        "original_price": 399000,
        "category": "Gia dụng",
        "rating": 4.4,
        "sold_count": 870,
        "stock": 45,
        "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=900&q=80",
        "variants": ["Trắng", "Xanh mint"],
        "tags": ["may xay", "gia dung", "suc khoe"],
    },
    {
        "id": "p012",
        "name": "Đèn bàn LED EyeCare",
        "slug": "den-ban-led-eyecare",
        "description": "Đèn học chống mỏi mắt, 3 nhiệt độ màu, cổ gập linh hoạt.",
        "price": 239000,
        "original_price": 320000,
        "category": "Gia dụng",
        "rating": 4.9,
        "sold_count": 1940,
        "stock": 101,
        "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
        "variants": ["Trắng", "Đen"],
        "tags": ["den ban", "hoc tap", "van phong"],
    },
    {
        "id": "p013",
        "name": "Bình giữ nhiệt ChillBottle 600ml",
        "slug": "binh-giu-nhiet-chillbottle-600ml",
        "description": "Giữ lạnh 18 giờ, giữ nóng 8 giờ, nắp chống rò rỉ.",
        "price": 199000,
        "original_price": 279000,
        "category": "Gia dụng",
        "rating": 4.8,
        "sold_count": 3650,
        "stock": 180,
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Trắng", "Xanh"],
        "tags": ["binh giu nhiet", "du lich", "van phong"],
    },
    {
        "id": "p014",
        "name": "Sổ tay Planner 2026",
        "slug": "so-tay-planner-2026",
        "description": "Planner tuần/tháng, giấy chống lem, bìa cứng tối giản.",
        "price": 129000,
        "original_price": 169000,
        "category": "Văn phòng",
        "rating": 4.6,
        "sold_count": 740,
        "stock": 88,
        "image_url": "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80",
        "variants": ["Xanh", "Be", "Đen"],
        "tags": ["so tay", "planner", "van phong"],
    },
    {
        "id": "p015",
        "name": "Bút gel SmoothNote set 6 cây",
        "slug": "but-gel-smoothnote-set-6-cay",
        "description": "Mực nhanh khô, nét 0.5mm, phù hợp ghi chú và học tập.",
        "price": 69000,
        "original_price": 99000,
        "category": "Văn phòng",
        "rating": 4.5,
        "sold_count": 4210,
        "stock": 260,
        "image_url": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Xanh", "Mix màu"],
        "tags": ["but", "hoc tap", "van phong"],
    },
    {
        "id": "p016",
        "name": "Loa Bluetooth PocketBass",
        "slug": "loa-bluetooth-pocketbass",
        "description": "Loa mini chống nước nhẹ, âm bass tốt trong tầm giá.",
        "price": 389000,
        "original_price": 520000,
        "category": "Điện tử",
        "rating": 4.6,
        "sold_count": 1180,
        "stock": 59,
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
        "variants": ["Đen", "Cam", "Xanh"],
        "tags": ["loa", "bluetooth", "duoi 500k"],
    },
]

FAQS = [
    {
        "id": "f001",
        "category": "Giao hàng",
        "question": "Shop giao hàng trong bao lâu?",
        "answer": "Nội thành thường 1-2 ngày, tỉnh thành khác 2-5 ngày tùy đơn vị vận chuyển.",
    },
    {
        "id": "f002",
        "category": "Giao hàng",
        "question": "Có miễn phí vận chuyển không?",
        "answer": "Đơn từ 499.000đ được miễn phí vận chuyển tiêu chuẩn trong chương trình demo.",
    },
    {
        "id": "f003",
        "category": "Đổi trả",
        "question": "Chính sách đổi trả như thế nào?",
        "answer": "Bạn có thể đổi trả trong 7 ngày nếu sản phẩm lỗi, sai mẫu hoặc còn nguyên tem nhãn.",
    },
    {
        "id": "f004",
        "category": "Thanh toán",
        "question": "Shop hỗ trợ hình thức thanh toán nào?",
        "answer": "Demo hỗ trợ COD và chuyển khoản. Khi triển khai thật có thể tích hợp ví điện tử.",
    },
    {
        "id": "f005",
        "category": "Bảo hành",
        "question": "Sản phẩm điện tử bảo hành bao lâu?",
        "answer": "Nhóm điện tử được bảo hành 6-12 tháng tùy sản phẩm, thông tin chi tiết nằm ở trang sản phẩm.",
    },
    {
        "id": "f006",
        "category": "Đơn hàng",
        "question": "Làm sao kiểm tra trạng thái đơn hàng?",
        "answer": "Bạn cung cấp mã đơn như OD1001, bot sẽ tra trạng thái đơn hàng demo cho bạn.",
    },
]

ORDERS = [
    {
        "id": "OD1001",
        "customer_name": "Nguyen An",
        "phone": "0901001001",
        "address": "12 Nguyen Trai, Quan 1, TP.HCM",
        "status": "Đang giao",
        "total_amount": 788000,
        "items": [
            {"product_id": "p001", "product_name": "Tai nghe Bluetooth AirBeat S3", "quantity": 1, "price": 459000},
            {"product_id": "p005", "product_name": "Pin dự phòng VoltGo 10000mAh", "quantity": 1, "price": 329000},
        ],
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "OD1002",
        "customer_name": "Tran Binh",
        "phone": "0902002002",
        "address": "88 Cau Giay, Ha Noi",
        "status": "Chờ xác nhận",
        "total_amount": 790000,
        "items": [
            {"product_id": "p002", "product_name": "Bàn phím cơ KPro Mini", "quantity": 1, "price": 790000},
        ],
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "OD1003",
        "customer_name": "Le Chi",
        "phone": "0903003003",
        "address": "25 Le Loi, Da Nang",
        "status": "Đã giao",
        "total_amount": 387000,
        "items": [
            {"product_id": "p008", "product_name": "Áo thun CottonFlex basic", "quantity": 2, "price": 159000},
            {"product_id": "p015", "product_name": "Bút gel SmoothNote set 6 cây", "quantity": 1, "price": 69000},
        ],
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
]


def get_product(product_id_or_slug: str):
    return next(
        (
            product
            for product in PRODUCTS
            if product["id"] == product_id_or_slug or product["slug"] == product_id_or_slug
        ),
        None,
    )


def get_categories():
    return sorted({product["category"] for product in PRODUCTS})


def get_order(order_id: str):
    return next((order for order in ORDERS if order["id"].lower() == order_id.lower()), None)
